### ISSUE TITLE
Make better use of reflection/homoiconicity

### ISSUE THREAD

**Issue by GabrielKS** [NREL-Sienna/InfrastructureSystems.jl#338]
[Another](https://github.com/NREL-Sienna/PowerSimulations.jl/issues/1043) catch-all issue for minor, low-priority refactors. There are some things we currently do using string manipulation, manually keeping track of lists of things, etc. that I think could be more elegantly accomplished using Julia's abilities to operate on itself. I'll start a list here:

**Comment by GabrielKS** [comment]
`strip_module_name` currently uses string manipulation to turn `PowerSystems.HydroDispatch` into `"HydroDispatch"`. There's a built-in Julia method that operates on types to do this:
```julia
julia> string(Base.nameof(PowerSystems.HydroDispatch))
"HydroDispatch"
```
There are probably more intricacies to figure out here but I'm pretty confident a reflection-based approach is feasible.

**Comment by GabrielKS** [comment]
[Sometimes](https://github.com/NREL-Sienna/InfrastructureSystems.jl/blob/596a75fa02ff3fba3f56283e833aa25af6739de2/src/hdf5_time_series_storage.jl#L295) we want to do the opposite, go from string to type, and currently we manually build a dictionary [to avoid using `eval`](https://github.com/NREL-Sienna/InfrastructureSystems.jl/blob/596a75fa02ff3fba3f56283e833aa25af6739de2/src/hdf5_time_series_storage.jl#L235). But there is a sort of inverse of `Base.nameof`:
```julia
julia> getproperty(PowerSystems, Symbol("HydroDispatch"))
PowerSystems.HydroDispatch
```
that I [don't think](https://github.com/GabrielKS/PowerAnalytics.jl/blob/3aa8d80359262bac9278cfd01db685a0d1e42b09/src/builtin_entities.jl#L12) has the same security risk as `eval`.

**Comment by daniel-thom** [comment]
Yes, we should use `nameof`. I noticed this function in Base at some point and started using it…but didn’t go back and change the old code.

Regarding this one:
```
julia> getproperty(PowerSystems, Symbol("HydroDispatch"))
PowerSystems.HydroDispatch
```
I’m not sure I follow what you’re referring to in the code, but we use this approach when de-serializing JSON to types. We store the module and type names as strings and then look them back in this way. It is safe.
